# Generated by Django 2.2.1 on 2019-06-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImeKategorije', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OdpiralniCas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teden', models.CharField(max_length=20)),
                ('vikend', models.CharField(max_length=20)),
                ('lokacija', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Zgodba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgodba', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlikaStvari', models.ImageField(blank=True, null=True, upload_to='item_pictures')),
                ('ImeStvari', models.CharField(max_length=20)),
                ('OpisStvari', models.TextField()),
                ('Kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Kategorija')),
            ],
        ),
    ]
